# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to GH Pages

on:
  push:
    branches: [ "develop" ]
  

jobs:
  build:
    name: Deploy to GH Pages
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    - run: npm i
    - run: npm ci
    - run: npm run build 
    - run : git config user.name github-actions
    - run : git config user.email github-actions@github.com
    - run : git --work-tree build add --all
    - run : git commit -m "Automatic Build and Deploy run by GitHub Actions"
    - run : git push origin HEAD:gh-pages --force

